# Use the official MongoDB image from the Docker Hub
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Set the working directory
WORKDIR /data/db

# Command to run MongoDB
CMD ["mongod", "--bind_ip_all"]
